---
title: Add support for updating the dev environment
category: added
author: Venu Vardhan Reddy Tekula <venu@bitergia.com>
issue: null
notes: >
    The support for updating the developer environment
    is added. This would be needed to update the repos
    by rebasing the latest changes with the upstream.

    It would open each folder, changes to `master` branch,
    and rebase the changes with the upstream.

    Usage:
    ```
    $ gareth -s sources --update
    ```
